theme = "harbor"
baseurl = "https://athos.github.io/"
title = "Uninterned Days"
paginate = 3
languageCode = "ja"
DefaultContentLanguage = "en"
hasCJKLanguage = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

# Optional
# If you use googleAnalytics, you set top-level options in config.toml to the beginning of the config file like other top-level options.
# googleAnalytics = "UA-XXXXXXXX-XX"
# and disqus too.
# disqusShortName = "yourdisqusshortname"

[Author]
  name = "athos"

[permalinks]
  post = "/post/:year/:month/:day/:filename"
  page = "/:filename"

[outputs]
  section = ["JSON", "HTML", "RSS"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "posts"
  name = "Posts"
  icon = "fas fa-list-alt fa-lg"
  url = "post"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3

# [[params.nav]]
#   identifier = "categories"
#   name = "Category"
#   icon = "fas fa-folder-open fa-lg"
#   url = "categories"
#   weight = 3

[[params.nav]]
  identifier = "rss"
  name = "RSS"
  icon = "fas fa-rss-square fa-lg"
  url = "index.xml"
  weight = 3

# [[params.nav]]
#   identifier = "search"
#   name = "Search"
#   icon = "fas fa-search fa-lg"
#   url = "search"
#   weight = 3

# copy paste this block and change for each social media to add how many ever social media
# acounts/links you want
[[params.social]]
  name="GitHub"
  url="https://github.com/athos"
  icon="fab fa-github"

[[params.social]]
  name="Twitter"
  url="https://twitter.com/athos0220"
  icon="fab fa-twitter"

[[params.social]]
  name="Mastodon"
  url="https://mstdn.jp/@athos"
  icon="fab fa-mastodon"

[params]
  mainSections = ["post"]
  customCSS = ["/css/custom.css"]

[params.logo]
  url = "DontCount.png" # static/images/icon.png
  width = 40
  height = 40
  alt = "Logo"
